

#BSUB -P sensitive_yli11_2020-01-07
#BSUB -o sensitive_yli11_2020-01-07/log_files/bw_%J_%I.out -e sensitive_yli11_2020-01-07/log_files/bw_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=2000]"
#BSUB -J "bw[1-11]"



module purge

id=$LSB_JOBINDEX
COL1=`head -n $id input.list|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id input.list|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id input.list|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id input.list|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id input.list|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id input.list|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id input.list|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id input.list|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id input.list|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id input.list|tail -n1`

ncore=1
mem=2000
module load python/2.7.13 ucsc/041619
bw_over_bed.py --extend ${COL1} -o ${COL2}

